type Test(_x: int, _y: bool, _z: int) :=
  member x: int := _x
  member y: bool := _y
  member z: int := _z
end

let x: int := 3 # not an error, Test's x is not in scope any longer
let t: Test := new Test(x, true, x - 1)

let start() :=
    printint(4)
